### ISSUE TITLE
你好，是不是缺少libsoundeditor.so文件？

### ISSUE THREAD

**Issue by wayuhan** [LKDont/SoundEditor#2]
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lkdont.soundeditor-7DUJ7y5rUosyCfhzC2gscg==/base.apk"],nativeLibraryDirectories=[/data/app/com.lkdont.soundeditor-7DUJ7y5rUosyCfhzC2gscg==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libsoundeditor.so"

**Comment by wayuhan** [comment]
Process: com.lkdont.soundeditor, PID: 27965
    java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.lkdont.soundeditor-7DUJ7y5rUosyCfhzC2gscg==/base.apk"],nativeLibraryDirectories=[/data/app/com.lkdont.soundeditor-7DUJ7y5rUosyCfhzC2gscg==/lib/arm64, /system/lib64, /system/product/lib64]]] couldn't find "libsoundeditor.so"
        at java.lang.Runtime.loadLibrary0(Runtime.java:1067)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.lkdont.soundeditor.MyApplication.onCreate(:17)
        at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1197)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6660)
        at android.app.ActivityThread.access$1700(ActivityThread.java:231)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1965)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7695)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)

**Comment by LKDont** [comment]
重新编译了FFmpeg的库，并更新了工程，现在应该没问题了。
